### ISSUE TITLE
Looks great! Any feedback after one year?

### ISSUE THREAD

**Issue by besarthoxhaj** [geowarin/retro-js#1]
Hi @geowarin!

Just trying out your [electron-hot-loader](https://github.com/geowarin/electron-hot-loader) and this boilerplate.

This looks great and is super fast!

Do you have any feedback after one year?

**Comment by geowarin** [comment]
Hey @besarthoxhaj !

It was definitely a fun project.
However, I don't use it anymore as I am no longer working on electron projects.

If you're looking for a very fast bundler I recommend [fuse-box](https://github.com/fuse-box/fuse-box-electron-seed).

**Comment by besarthoxhaj** [comment]
@geowarin thanks for the suggestion, will have a look!:)
